### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by noinip** [AustinHasten/PlexHolidays#2]
Looks like I'm having a problem connecting

```
Traceback (most recent call last):
  File "main.py", line 216, in <module>
    ph = PlexHolidays()
  File "main.py", line 166, in __init__
    self.plex = Plex()
  File "main.py", line 21, in __init__
    self.account = self.get_account()
  File "main.py", line 36, in get_account
    account = MyPlexAccount(username, password)
  File "/usr/local/lib/python3.5/dist-packages/plexapi/myplex.py", line 79, in __init__
    data, initpath = self._signin(username, password, timeout)
  File "/usr/local/lib/python3.5/dist-packages/plexapi/myplex.py", line 87, in _signin
    data = self.query(self.SIGNIN, method=self._session.post, auth=(username, password), timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/plexapi/myplex.py", line 152, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='my.plexapp.com', port=443): Max retries exceeded with url: /users/sign_in.xml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2afda86ce4a8>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by SaulFemm** [comment]
I've seen this once in a blue moon. I only had to retry to get passed it. Would you mind trying the current version and letting me know if the problem persists? Also, were you on the same LAN as the server?
